### ISSUE TITLE
"CROSSSLOT Keys in request don't hash to the same slot" error

### ISSUE THREAD

**Issue by rbroggi** [beatlabs/harvester#111]
## Is your feature request related to a problem? Please describe

In method `getValues` in `monitor/redis/watcher.go:74` the method `MGet` cannot be used with an arbitrary set of keys as this leads to an error: `CROSSSLOT Keys in request don't hash to the same slot`, which means that MGet can only be used for set of keys that hash to the same slot.

**Comment by rbroggi** [comment]
Simple alternative:

```go
func (w *Watcher) getValues(ctx context.Context, ch chan<- []*change.Change) {
	values := make([]interface{}, len(w.keys))
	for i, key := range w.keys {
		v, err := w.client.Get(ctx, key).Result()
		if err != nil {
			log.Errorf("failed to Get value for key %s: %s", key, err)
			return
		}
		values[i] = v
	}

	changes := make([]*change.Change, 0, len(w.keys))

	for i, key := range w.keys {
		if values[i] == nil {
			continue
		}

		value := values[i].(string)
		hash := w.hash(value)
		if hash == w.hashes[i] {
			continue
		}

		w.versions[i]++
		w.hashes[i] = hash

		changes = append(changes, change.New(config.SourceRedis, key, value, w.versions[i]))
	}

	if len(changes) == 0 {
		return
	}

	ch <- changes
}
```

**Comment by rbroggi** [comment]
same code can be done with go-routines

**Comment by mantzas** [comment]
> same code can be done with go-routines

I would suggest to start without goroutines because it might has side effects with a lot of settings, until it becomes a problem of course.

**Comment by rbroggi** [comment]
alright, no problem for me.

**Comment by aziule** [comment]
I think we should give the user the possibility to provide a config flag to either use a single instance mode (with MGET) or cluster mode (with GETs).

**Comment by mantzas** [comment]
That would be a too complex thing and not so nice API wise.
We had to explain when to sue what, etc.

**Comment by aziule** [comment]
I fully agree that it adds complexity, but multiple GET will have an impact for users with lots of keys

**Comment by mantzas** [comment]
Not necessarily. We  are talking about how fast to update a setting change which might be ok to take some time e.g. 10s of seconds to minute.

**Comment by rbroggi** [comment]
As an example our application uses polling interval of 5mins (quite high) in almost all environments. The only exception is local environment where we increase the polling frequency by having a period of 50 milliseconds ( which might be a bit tight to fulfill multiple roundtrips between the service and redis). In any case, I have tested that our local integration tests work even with this high frequency (keep in mind that we only have 3 redis configurations)
