### ISSUE TITLE
Changing Watcher interface for avoiding race-conditions 

### ISSUE THREAD

**Issue by rbroggi** [beatlabs/harvester#112]
## Is your feature request related to a problem? Please describe

currently we have the following interface:

```go
type Watcher interface {
	Watch(ctx context.Context, ch chan<- []*change.Change) error
}
```

This interface is a smell because it opens the possibility for someone different than the data-producer to close the channel - this situation is dangerous because it can lead to:

1. race-conditions
2. panics in case the Watcher tries to watch a closed channel

I suggest to adapt the interface as:

```go
type Watcher interface {
	Watch(ctx context.Context)  <-chan []*change.Change, error
}
```

**Comment by rbroggi** [comment]
I don't think so... the watcher seems to only be used internally but you are right to say that it is an exported interface and so yes!

**Comment by rbroggi** [comment]
let me see if anyone is using it

**Comment by rbroggi** [comment]
For sure! 

Well, I would in any case enforce this breaking change and also would make 

```go
type Watcher interface {
	Watch(ctx context.Context, ch chan<- []*change.Change) error
}
```

```go
type watcher interface {
	Watch(ctx context.Context, ch chan<- []*change.Change) error
}
```

**Comment by mantzas** [comment]
As discussed in the PR this seems not to be really beneficial.
