### ISSUE TITLE
Seeder best effort

### ISSUE THREAD

**Issue by GerardRodes** [beatlabs/harvester#128]
## Is your feature request related to a problem? Please describe

For testing purposes I would like to have the ability to reseed my config from seeds defined in field tags, ignoring any external seeders like Redis or Consul.

Right now this makes the seeded to fail and return with the config struct half seeded because when it encounters a field with an external seeder that has not been provided like Redis it stops execution there.

## Describe the solution

We could make `seeder.Seed` to do not return an error if an external seeder is not available by:
1. making the method best effort by default
or
2. adding a `bestEffort` flag as an argument to `seeder.Seed`

**Comment by mantzas** [comment]
After a discussion we found a way to solve our problem without harvester changes. closing the issue and PR.
