### ISSUE TITLE
Set harvester log level

### ISSUE THREAD

**Issue by legendary-cookie** [beatlabs/harvester#148]
## Is your feature request related to a problem? Please describe

I want to set the log level of your logging to a non-DEBUG value. 

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Run `harvester.Harvest` for anything

## Describe the solution

A way to set log level.

**Comment by mantzas** [comment]
Hey,
you can actually provide your own logging implementation via the log package of Harvester.
Check out this set-up [function](https://github.com/beatlabs/harvester/blob/dee91cad972ad15e80d8230f259465823c760be6/log/log.go#L30) of the logging package.
Hope this helps.

**Comment by legendary-cookie** [comment]
Nice, I'll check that out!

**Comment by legendary-cookie** [comment]
Thanks, got everything setup!
