### ISSUE TITLE
Nesting support for config struct

### ISSUE THREAD

**Issue by mantzas** [beatlabs/harvester#16]
## Is your feature request related to a problem? Please describe

At this point harvester supports only one level in configuration structs.
It might be interesting to see support for nested struct.

## Describe the solution

Each field in the struct should be checked for being a struct which contains the sync packages types.

**Comment by Oberonus** [comment]
Hi @mantzas, do you accept external pull requests on this issue? If yes, I'd like to contribute. I've made some changes in fork and in general it looks like a working solution, the only thing remained is to make a PR.

**Comment by mantzas** [comment]
@Oberonus Hi, yes you are more than welcome to contribute.
