### ISSUE TITLE
Vault support

### ISSUE THREAD

**Issue by mantzas** [beatlabs/harvester#26]
## Is your feature request related to a problem? Please describe

Secrets management is very important for security. Reading secrets from Vault will solve this problem.
We need support for Vault in the seeing phase.

## Describe the solution

- Add struct tags for Vault
- Add seed support for Vault

**Comment by siavashs** [comment]
[Vault Injector](https://www.vaultproject.io/docs/platform/k8s/injector) can provide the secrets in the application environment as variables or files.
So it's possible to integrate with Vault using existing implementation without needing to support it internally in Harvester.

**Comment by mantzas** [comment]
Yes that could be also an option but since we already handling configuration through harvester for env vars, our configuration management systems i would make more sense to have it in one place.
It would make our architecture also much simpler.
Keeps also in mind that testing is not possible if we are not running inside k8s with your proposal and local development would not work at all.

**Comment by mantzas** [comment]
Seems like there are better ways to handle that, so closing it for now.
