### ISSUE TITLE
Add support for user defined custom types

### ISSUE THREAD

**Issue by Oberonus** [beatlabs/harvester#38]
## Is your feature request related to a problem? Please describe

Perhaps it could be a good idea to give library users an ability to define and use their own custom field types, not limiting only to predefined `sync` package.

It could be used for example to:

1. Add any kind of custom seeding stage validation
2. Make complex value types (for example, config string "user@example.com" could be translated at user defined struct ```{Name:”user”, Host:”example.com”}``` automatically on seeding stage

## Describe the solution
Core idea - rely on interface, not on reflection based setter/stringer methods.

1. Decouple `config.Value` and `sync` package types by moving the responsibility to set a string typed value to the `sync` types themselves. It could be done introducing something like `SetString(string) error` inside each type.
2. Replace reflection based `setter` and `printer` fields of the `sync.Field` with `CfgField` interface
3. Require that any new custom type structure must implement the `CfgField` interface and be thread safe
4. Change behaviour on nesting config structs:
    1. If struct field has seeding tags, it MUST implement `CfgField` interface and it is tracked as a source for `config.Field`.
    2. If there are not seeding tags, this struct considered as a nested structure

`CfgField` interface could look like:

```go
type CfgField interface {
	//golang stringer interface
	fmt.Stringer
	//setter from string value, should parse string 
	//to the underlying type and set a value, or return an error
	SetString(value string) error
}
```

**Comment by mantzas** [comment]
@Oberonus There is one small problem here. How can we make sure that the types provided are goroutine safe? The sync package actually reassures us of that...

**Comment by Oberonus** [comment]
> @Oberonus There is one small problem here. How can we make sure that the types provided are goroutine safe? The sync package actually reassures us of that...

Yes, there is no 100% guarantee that user will not shoot in his knee. I've mentioned, that there are three requirements for any custom type and of course it have to be documented:
- It must be a struct type
- It must implement required interface
- It must be thread safe, since setter/getter could be called concurrently

The only way that comes to my mind right now is to make things more strict - require to use our builder for creating this fields, that will somehow make a wrapper (proxy) for user type and make it thread safe. But even with this approach it is impossible to make it completely free from improper use, since there could be other user methods or field itself could be made public.

IMO since any customisation process that involves externally created logic could be improperly used, there have to be clear requirements documented with information on how to use this tool.

Of course, if this library have to be 100% safe for any possible cases of wrong usage, it could be a serious issue. And in this case perhaps it is better to leave strict rules about `sync` package as it is.

What do you think?

**Comment by mantzas** [comment]
We can just say: "use your own types at your own risk" and be done with it... we can guaratee only for our types.

**Comment by Oberonus** [comment]
> We can just say: "use your own types at your own risk" and be done with it... we can guaratee only for our types.

To help as much as we can with proper documentation and examples and add this disclaimer as a warning. Yep.

**Comment by c0nstantx** [comment]
@mantzas @Oberonus We could try enforce it indirectly by asking the new structs to comply also to [Locker](https://golang.org/pkg/sync/#Locker) interface, which our own structs already follow. Another way could be to add specific functions in our `CfgField` interface for read/write lock.

Of course, since this is in the discretion of the developer to use, we must add the proper documentation and warnings as you already mentioned

**Comment by mantzas** [comment]
@c0nstantx, unfortunately, we cannot because in our types lock and unlock are not (and should not be) exported.
