### ISSUE TITLE
Add support for time.Duration

### ISSUE THREAD

**Issue by m0th517** [beatlabs/harvester#44]
## Is your feature request related to a problem? Please describe

It would be very convenient to be able to specify the type of a harvester field as sync.Duration.
Fields describing a time duration are very common in configuration and having the ability to directly parse a specially formatted string as Go's time.Duration time would be very handy to have.

## Describe the solution

The expected string should be a valid format that time.ParseDuration can handle:
`ParseDuration parses a duration string. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h". `

A new sync.Duration field will be created, which wraps a time.Duration value type. sync.Duration will be identical to sync.Int64 but casted as time.Duration (which is an int64) for better code readability.

In harvester's config.Field.Set() the string is parsed using time.ParseDuration.

## Additional context

Current workaround if configuration includes durations in Go's duration format is to use a sync.String field and parse it manually when needed. Obviously, any binding with a consul field will not update changes live if the duration has been parsed in a different variable.

**Comment by mantzas** [comment]
@ArisKostakos There was also a feature #38 added to Harvester that handles custom types by @Oberonus. Would you like to take a look?
You can start with this custom type and if it makes sense we can do a PR later.

**Comment by ArisKostakos** [comment]
Sounds good, we'll look into custom types.
