### ISSUE TITLE
Harvester logs secret values 

### ISSUE THREAD

**Issue by peterklijn** [beatlabs/harvester#47]
## Is your feature request related to a problem? Please describe

When harvester parses the configuration, it logs the the values it finds. This is nice for debugging, but these secrets now end up in our logging, which is not good from a security perspective.

Example logs:

```
2020/04/06 13:51:19 INFO: field IndexName updated with value customers-v1, version: 0
2020/04/06 13:51:19 INFO: seed value customers-v1 applied on field IndexName
2020/04/06 13:51:19 INFO: field CacheRetention updated with value 43200, version: 0
2020/04/06 13:51:19 INFO: seed value 43200 applied on field CacheRetention
2020/04/06 13:51:19 INFO: field CacheRetention updated with value 86400, version: 0
2020/04/06 13:51:19 INFO: env var value 86400 applied on field CacheRetention
2020/04/06 13:51:19 INFO: field LogLevel updated with value DEBUG, version: 0
2020/04/06 13:51:19 INFO: seed value DEBUG applied on field LogLevel
2020/04/06 13:51:19 WARN: flag var loglevel did not exist for field LogLevel
2020/04/06 13:51:19 Config : IndexName: customers-v1, CacheRetention: 86400, LogLevel: DEBUG

```

## Is this a bug? Please provide steps to reproduce, a failing test etc.

Start any of the example projects, the logs above are from `01_basic`

## Describe the solution

Mark specific values as secrets, and mask (part of) their values.

**Comment by c0nstantx** [comment]
@peterklijn For that reason we have the type `sync.Secret`

**Comment by peterklijn** [comment]
Thanks @c0nstantx, I totally missed that 😅
