### ISSUE TITLE
supporting time duration as configurable field

### ISSUE THREAD

**Issue by YafimK** [beatlabs/harvester#64]
Preparation for contribution

## Is your feature request related to a problem? Please describe

Use time.duration as supported configurable field

## Describe the solution

Allow to parse and import key value with time.Duration as type

**Comment by mantzas** [comment]
Hi, we had already a discussion about this. Would you like to check https://github.com/beatlabs/harvester/issues/44?

**Comment by YafimK** [comment]
Thanks! sorry for the DUP. For some reason, GitHub search didn't pop this up. Anyway - i've made some initial implementation doing exactly that. still have some work on it #65. I'm adding tests and I'll update the docs as mentioned.
